mod activity;
mod ai;
mod backup;
mod commands;
mod db;
mod error;
mod export;
mod fakturoid;
mod invoice;
mod models;
mod repo;
mod secrets;
mod tracker;

use std::sync::{Arc, Mutex, RwLock};
use std::time::Duration;

use tauri::menu::{Menu, MenuBuilder, MenuItem, MenuItemBuilder, SubmenuBuilder};
use tauri::tray::{MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent};
use tauri::{AppHandle, Emitter, Manager, RunEvent, WindowEvent, Wry};
use tauri_specta::{collect_commands, Builder, ErrorHandlingMode};

use commands::AppState;
use tracker::TrackerConfig;

fn specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            commands::list_clients,
            commands::create_client,
            commands::update_client,
            commands::delete_client,
            commands::list_entries,
            commands::day_totals,
            commands::create_entry,
            commands::update_entry,
            commands::delete_entry,
            commands::get_settings,
            commands::save_settings,
            commands::set_secret,
            commands::has_secret,
            commands::open_accessibility_settings,
            commands::open_url,
            commands::get_day_activity,
            commands::tracked_days,
            commands::get_day_summary,
            commands::list_day_summaries,
            commands::list_tags,
            commands::generate_day_summary,
            commands::suggest_entry,
            commands::fakturoid_accounts,
            commands::fakturoid_subjects,
            commands::fakturoid_generators,
            commands::preview_invoice,
            commands::create_invoice,
            commands::export_csv,
            commands::list_backups,
            commands::backup_now,
            commands::restore_backup,
            commands::app_paths,
            commands::show_main_window,
        ])
        .error_handling(ErrorHandlingMode::Throw)
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = specta_builder();

    #[cfg(debug_assertions)]
    builder
        .export(
            specta_typescript::Typescript::new()
                .header("// Generated by tauri-specta. Do not edit.\n"),
            "../src/bindings.ts",
        )
        .expect("failed to export typescript bindings");

    tauri::Builder::default()
        .plugin(tauri_plugin_log::Builder::new().level(log::LevelFilter::Info).build())
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_autostart::init(
            tauri_plugin_autostart::MacosLauncher::LaunchAgent,
            None,
        ))
        .invoke_handler(builder.invoke_handler())
        .on_menu_event(|app, event| {
            let id = event.id.as_ref();
            if id.starts_with("nav:") || id == "new-entry" {
                show_main(app);
                let _ = app.emit("menu-action", id);
            }
        })
        .setup(move |app| {
            builder.mount_events(app);
            app.set_menu(build_menu(app.handle())?)?;

            let app_data_dir = app.path().app_data_dir()?;
            std::fs::create_dir_all(&app_data_dir)?;
            let db_path = app_data_dir.join("flowrly.db");

            match backup::apply_pending_restore(&db_path) {
                Ok(true) => log::info!("restored database from staged backup"),
                Ok(false) => {}
                Err(e) => log::error!("restore failed: {e}"),
            }

            let conn = db::open(&db_path)?;
            let settings = repo::load_settings(&conn)?;

            let tracker_cfg = Arc::new(RwLock::new(TrackerConfig {
                enabled: settings.tracking_enabled,
                idle_threshold_secs: settings.idle_threshold_seconds.max(30) as u64,
                ignored_apps: settings.ignored_apps.clone(),
            }));
            tracker::spawn(db_path.clone(), tracker_cfg.clone());

            let state = AppState {
                db: Mutex::new(conn),
                db_path,
                app_data_dir: app_data_dir.clone(),
                tracker_cfg,
                http: reqwest::Client::builder()
                    .timeout(Duration::from_secs(30))
                    .build()
                    .expect("reqwest client"),
                fakturoid_tokens: Default::default(),
            };
            commands::apply_settings(app.handle(), &state, &settings);
            app.manage(state);

            // Backups: on launch, then hourly check for a 24h-old snapshot.
            let handle = app.handle().clone();
            tauri::async_runtime::spawn(async move {
                loop {
                    backup_if_due(&handle.state::<AppState>());
                    tokio::time::sleep(Duration::from_secs(3600)).await;
                }
            });

            // Tray
            let open = MenuItem::with_id(app, "open", "Open Flowrly", true, None::<&str>)?;
            let quit = MenuItem::with_id(app, "quit", "Quit Flowrly", true, None::<&str>)?;
            let menu = Menu::with_items(app, &[&open, &quit])?;
            let mut tray = TrayIconBuilder::with_id("main")
                .menu(&menu)
                .show_menu_on_left_click(false)
                .tooltip("Flowrly")
                .on_menu_event(|app, event| match event.id.as_ref() {
                    "open" => show_main(app),
                    "quit" => app.exit(0),
                    _ => {}
                })
                .on_tray_icon_event(|tray, event| {
                    if let TrayIconEvent::Click { button: MouseButton::Left, button_state: MouseButtonState::Up, .. } = event {
                        show_main(tray.app_handle());
                    }
                });
            // Monochrome template image: macOS tints it white/black to match the menu bar.
            match tauri::image::Image::from_bytes(include_bytes!("../icons/tray@2x.png")) {
                Ok(icon) => tray = tray.icon(icon).icon_as_template(true),
                Err(e) => {
                    log::warn!("tray icon: {e}");
                    if let Some(icon) = app.default_window_icon() {
                        tray = tray.icon(icon.clone());
                    }
                }
            }
            tray.build(app)?;

            Ok(())
        })
        .on_window_event(|window, event| {
            if let WindowEvent::CloseRequested { api, .. } = event {
                api.prevent_close();
                let _ = window.hide();
            }
        })
        .build(tauri::generate_context!())
        .expect("error while building tauri application")
        .run(|app, event| {
            // Dock click or relaunch while the window is hidden in the tray.
            if let RunEvent::Reopen { has_visible_windows, .. } = event {
                log::info!("reopen (visible windows: {has_visible_windows})");
                show_main(app);
            }
        });
}

fn backup_if_due(state: &AppState) {
    let Ok(conn) = state.conn() else { return };
    let dir = repo::load_settings(&conn)
        .map(|s| backup::resolve_dir(&state.app_data_dir, &s.backup_dir))
        .unwrap_or_else(|_| state.app_data_dir.join("backups"));
    let due = backup::newest_age(&dir)
        .map(|age| age >= Duration::from_secs(24 * 3600))
        .unwrap_or(true);
    if due {
        match backup::create(&conn, &dir) {
            Ok(b) => log::info!("backup written: {}", b.path),
            Err(e) => log::error!("backup failed: {e}"),
        }
    }
}

/// App menu with a "Go" submenu listing every shortcut. Items with ids
/// `nav:<path>` / `new-entry` are forwarded to the webview as `menu-action`.
fn build_menu(app: &AppHandle) -> tauri::Result<Menu<Wry>> {
    let item = |id: &str, label: &str, accel: &str| MenuItemBuilder::with_id(id, label).accelerator(accel).build(app);

    let app_menu = SubmenuBuilder::new(app, "Flowrly")
        .about(None)
        .separator()
        .item(&item("nav:/settings", "Settings…", "Cmd+,")?)
        .separator()
        .services()
        .separator()
        .hide()
        .hide_others()
        .show_all()
        .separator()
        .quit()
        .build()?;
    let file = SubmenuBuilder::new(app, "File").close_window().build()?;
    let edit = SubmenuBuilder::new(app, "Edit")
        .undo()
        .redo()
        .separator()
        .cut()
        .copy()
        .paste()
        .select_all()
        .build()?;
    let view = SubmenuBuilder::new(app, "View").fullscreen().build()?;
    let go = SubmenuBuilder::new(app, "Go")
        .item(&item("new-entry", "Log Time", "Cmd+N")?)
        .separator()
        .item(&item("nav:/", "Calendar", "Cmd+1")?)
        .item(&item("nav:/entries", "Entries", "Cmd+2")?)
        .item(&item("nav:/dashboard", "Activity", "Cmd+3")?)
        .item(&item("nav:/clients", "Clients", "Cmd+4")?)
        .item(&item("nav:/settings", "Settings", "Cmd+5")?)
        .build()?;
    let window = SubmenuBuilder::new(app, "Window").minimize().maximize().separator().close_window().build()?;

    MenuBuilder::new(app).items(&[&app_menu, &file, &edit, &view, &go, &window]).build()
}

fn show_main(app: &tauri::AppHandle) {
    if let Some(w) = app.get_webview_window("main") {
        let _ = w.show();
        let _ = w.unminimize();
        let _ = w.set_focus();
    }
}

#[cfg(test)]
mod tests {
    #[test]
    fn export_bindings() {
        super::specta_builder()
            .export(
                specta_typescript::Typescript::new().header("// Generated by tauri-specta. Do not edit.\n"),
                "../src/bindings.ts",
            )
            .expect("export bindings");
    }
}
