// Generated by tauri-specta. Do not edit.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	listClients: () => __TAURI_INVOKE<Client[]>("list_clients"),
	createClient: (input: ClientInput) => __TAURI_INVOKE<Client>("create_client", { input }),
	updateClient: (id: number, input: ClientInput) => __TAURI_INVOKE<Client>("update_client", { id, input }),
	deleteClient: (id: number) => __TAURI_INVOKE<null>("delete_client", { id }),
	listEntries: (filter: EntryFilter) => __TAURI_INVOKE<TimeEntry[]>("list_entries", { filter }),
	dayTotals: (from: string, to: string) => __TAURI_INVOKE<DayTotal[]>("day_totals", { from, to }),
	createEntry: (input: TimeEntryInput) => __TAURI_INVOKE<TimeEntry>("create_entry", { input }),
	updateEntry: (id: number, input: TimeEntryInput) => __TAURI_INVOKE<TimeEntry>("update_entry", { id, input }),
	deleteEntry: (id: number) => __TAURI_INVOKE<null>("delete_entry", { id }),
	getSettings: () => __TAURI_INVOKE<Settings>("get_settings"),
	saveSettings: (settings: Settings) => __TAURI_INVOKE<Settings>("save_settings", { settings }),
	setSecret: (key: SecretKey, value: string) => __TAURI_INVOKE<null>("set_secret", { key, value }),
	hasSecret: (key: SecretKey) => __TAURI_INVOKE<boolean>("has_secret", { key }),
	openAccessibilitySettings: () => __TAURI_INVOKE<null>("open_accessibility_settings"),
	openUrl: (url: string) => __TAURI_INVOKE<null>("open_url", { url }),
	getDayActivity: (day: string) => __TAURI_INVOKE<DayActivity>("get_day_activity", { day }),
	trackedDays: (from: string, to: string) => __TAURI_INVOKE<TrackedDay[]>("tracked_days", { from, to }),
	getDaySummary: (day: string) => __TAURI_INVOKE<{
	day: string,
	active_minutes: number,
	description: string,
	tags: TagMinutes[],
	generated_at: string,
} | null>("get_day_summary", { day }),
	listDaySummaries: (from: string, to: string) => __TAURI_INVOKE<DaySummary[]>("list_day_summaries", { from, to }),
	listTags: () => __TAURI_INVOKE<string[]>("list_tags"),
	generateDaySummary: (day: string) => __TAURI_INVOKE<DaySummary>("generate_day_summary", { day }),
	suggestEntry: (day: string) => __TAURI_INVOKE<Suggestion>("suggest_entry", { day }),
	fakturoidAccounts: () => __TAURI_INVOKE<FakturoidAccount[]>("fakturoid_accounts"),
	fakturoidSubjects: () => __TAURI_INVOKE<FakturoidSubject[]>("fakturoid_subjects"),
	fakturoidGenerators: () => __TAURI_INVOKE<FakturoidGenerator[]>("fakturoid_generators"),
	previewInvoice: (filter: EntryFilter) => __TAURI_INVOKE<InvoicePreview>("preview_invoice", { filter }),
	createInvoice: (filter: EntryFilter) => __TAURI_INVOKE<CreatedInvoice>("create_invoice", { filter }),
	exportCsv: (filter: EntryFilter, path: string) => __TAURI_INVOKE<number>("export_csv", { filter, path }),
	listBackups: () => __TAURI_INVOKE<BackupFile[]>("list_backups"),
	backupNow: () => __TAURI_INVOKE<BackupFile>("backup_now"),
	restoreBackup: (path: string) => __TAURI_INVOKE<null>("restore_backup", { path }),
	appPaths: () => __TAURI_INVOKE<string[]>("app_paths"),
	showMainWindow: () => __TAURI_INVOKE<null>("show_main_window"),
};

/* Types */
export type ActivityBlock = {
	app: string,
	title: string,
	minutes: number,
};

export type AiProvider = "anthropic" | "openai" | "gemini" | "openrouter" | "ollama";

export type AppError = { kind: "Db"; message: string } | { kind: "NotFound"; message: string } | { kind: "Validation"; message: string } | { kind: "Fakturoid"; message: string } | { kind: "Ai"; message: string } | { kind: "Io"; message: string } | { kind: "Secret"; message: string } | { kind: "Internal"; message: string };

export type AppMinutes = {
	app: string,
	minutes: number,
};

export type BackupFile = {
	path: string,
	name: string,
	size_bytes: number,
	created_at: string,
};

export type Client = {
	id: number,
	name: string,
	color: string,
	hourly_rate: number | null,
	/**  ISO 4217 code, e.g. "CZK". */
	currency: string,
	/**  Contractual workload share for this client, 0-100. */
	pensum_percent: number,
	/**  Hours in a full working day, e.g. 8.5. */
	workday_hours: number | null,
	vat_rate: number,
	line_description: string,
	fakturoid_subject_id: number | null,
	fakturoid_generator_id: number | null,
	archived: boolean,
};

export type ClientInput = {
	name: string,
	color: string,
	hourly_rate: number | null,
	currency: string,
	pensum_percent: number,
	workday_hours: number | null,
	vat_rate: number,
	line_description: string,
	fakturoid_subject_id: number | null,
	fakturoid_generator_id: number | null,
	archived: boolean,
};

export type CreatedInvoice = {
	id: number,
	number: string,
	html_url: string,
	total: string,
};

/**  Raw, un-summarised overview of a day: what the tracker saw. */
export type DayActivity = {
	day: string,
	active_minutes: number,
	idle_minutes: number,
	first_active: string | null,
	last_active: string | null,
	sample_count: number,
	/**  Focused windows, most time first (capped). */
	top_blocks: ActivityBlock[],
	/**  Active minutes per app, most time first (complete). */
	apps: AppMinutes[],
	/**  Active minutes for each hour of the day, index 0..24. */
	per_hour: number[],
};

export type DaySummary = {
	day: string,
	active_minutes: number,
	description: string,
	tags: TagMinutes[],
	generated_at: string,
};

export type DayTotal = {
	date: string,
	client_id: number,
	minutes: number,
};

export type EntryFilter = {
	client_id: number | null,
	/**  Inclusive, YYYY-MM-DD */
	from: string | null,
	/**  Inclusive, YYYY-MM-DD */
	to: string | null,
};

export type FakturoidAccount = {
	slug: string,
	name: string,
};

export type FakturoidGenerator = {
	id: number,
	name: string,
	subject_id: number | null,
};

export type FakturoidSubject = {
	id: number,
	name: string,
	registration_no: string | null,
};

export type InvoicePreview = {
	client_id: number,
	period_label: string,
	line_name: string,
	total_minutes: number,
	hours: number | null,
	hourly_rate: number | null,
	currency: string,
	vat_rate: number,
	subtotal: number | null,
	entry_count: number,
};

export type SecretKey = "fakturoid_client_secret" | "ai_api_key";

export type Settings = {
	ai_provider: AiProvider,
	ai_model: string,
	ai_base_url: string,
	fakturoid_client_id: string,
	fakturoid_account_slug: string,
	fakturoid_contact_email: string,
	tracking_enabled: boolean,
	idle_threshold_seconds: number,
	ignored_apps: string[],
	backup_dir: string,
	launch_at_login: boolean,
};

export type Suggestion = {
	start_time: string | null,
	end_time: string | null,
	duration_minutes: number,
	description: string,
};

export type TagMinutes = {
	tag: string,
	minutes: number,
};

export type TimeEntry = {
	id: number,
	client_id: number,
	/**  YYYY-MM-DD */
	date: string,
	duration_minutes: number,
	/**  HH:MM */
	start_time: string | null,
	/**  HH:MM */
	end_time: string | null,
	description: string,
};

export type TimeEntryInput = {
	client_id: number,
	date: string,
	/**  Ignored (recomputed) when both start_time and end_time are present. */
	duration_minutes: number,
	start_time: string | null,
	end_time: string | null,
	description: string,
};

export type TrackedDay = {
	day: string,
	active_minutes: number,
	has_summary: boolean,
};

